### 把原資料篩出只有公館的

In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

youbike_df = pd.read_csv('./202210_YouBike2.0票證刷卡資料.csv')
youbike_df.dropna(inplace=True)

In [104]:
youbike_guan_df = youbike_df[youbike_df["rent_station"].str.contains("捷運公館站")]
station_list = []
for i in range(len(youbike_guan_df)):
    if youbike_guan_df.iloc[i, 1] == "捷運公館站(2號出口)":
        station_list.append("500101022")
    elif youbike_guan_df.iloc[i, 1] == "捷運公館站(3號出口)":
        station_list.append("500101181")
    elif youbike_guan_df.iloc[i, 1] == "捷運公館站(4號出口)":
        station_list.append("500106004")
    elif youbike_guan_df.iloc[i, 1] == "捷運公館站(1號出口)":
        station_list.append("500106003")
youbike_guan_df["rent_station_id"] = station_list
youbike_guan_df

<ipython-input-104-67d460a290bf>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youbike_guan_df["rent_station_id"] = station_list

,rent_time,rent_station,return_time,return_station,rent,infodate,rent_station_id
3345,2022-10-27 07:00:00,捷運公館站(2號出口),2022-10-27 08:00:00,基隆長興路口東側,00:14:02,2022-10-27,500101022
3346,2022-10-27 07:00:00,捷運公館站(2號出口),2022-10-27 08:00:00,師範大學公館校區,00:05:47,2022-10-27,500101022
3347,2022-10-27 08:00:00,捷運公館站(2號出口),2022-10-27 08:00:00,臺大男一舍前,00:04:08,2022-10-27,500101022
3348,2022-10-27 07:00:00,捷運公館站(2號出口),2022-10-27 08:00:00,臺大生命科學館西北側,00:08:51,2022-10-27,500101022
3349,2022-10-27 08:00:00,捷運公館站(2號出口),2022-10-27 08:00:00,臺大立體機車停車場,00:06:37,2022-10-27,500101022
...,...,...,...,...,...,...,...
2424526,2022-10-24 14:00:00,捷運公館站(4號出口),2022-10-24 14:00:00,臺大第一活動中心西南側,00:05:49,2022-10-24,500106004
2424527,2022-10-24 19:00:00,捷運公館站(4號出口),2022-10-24 19:00:00,臺大工綜館南側,00:04:25,2022-10-24,500106004
2424528,2022-10-24 19:00:00,捷運公館站(4號出口),2022-10-24 19:00:00,捷運臺電大樓站(2號出口)_1,00:08:02,2022-10-24,500106004
2424529,2022-10-24 20:00:00,捷運公館站(4號出口),2022-10-24 20:00:00,汀州思源街口東南側,00:22:19,2022-10-24,500106004
2424530,2022-10-24 21:00:00,捷運公館站(4號出口),2022-10-24 21:00:00,臺大水源舍區A棟,00:03:21,2022-10-24,500106004

In [105]:
youbike_guan_df2 = youbike_df[youbike_df["return_station"].str.contains("捷運公館站")]
station_list = []
for i in range(len(youbike_guan_df2)):
    if youbike_guan_df2.iloc[i, 3] == "捷運公館站(2號出口)":
        station_list.append("500101022")
    elif youbike_guan_df2.iloc[i, 3] == "捷運公館站(3號出口)":
        station_list.append("500101181")
    elif youbike_guan_df2.iloc[i, 3] == "捷運公館站(4號出口)":
        station_list.append("500106004")
    elif youbike_guan_df2.iloc[i, 3] == "捷運公館站(1號出口)":
        station_list.append("500106003")
youbike_guan_df2["return_station_id"] = station_list
youbike_guan_df2

<ipython-input-105-3abe2864c6d7>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youbike_guan_df2["return_station_id"] = station_list

,rent_time,rent_station,return_time,return_station,rent,infodate,return_station_id
677,2022-10-27 07:00:00,臺北市藝文推廣處,2022-10-27 07:00:00,捷運公館站(2號出口),00:26:28,2022-10-27,500101022
1387,2022-10-27 17:00:00,羅斯福路二段6巷口,2022-10-27 17:00:00,捷運公館站(1號出口),00:08:54,2022-10-27,500106003
1737,2022-10-27 16:00:00,重慶南海路口西南側,2022-10-27 16:00:00,捷運公館站(3號出口),00:24:30,2022-10-27,500101181
1814,2022-10-27 16:00:00,螢橋國小,2022-10-27 16:00:00,捷運公館站(1號出口),00:15:50,2022-10-27,500106003
2211,2022-10-27 00:00:00,水源路11-1號旁,2022-10-27 00:00:00,捷運公館站(1號出口),00:07:04,2022-10-27,500106003
...,...,...,...,...,...,...,...
2428785,2022-10-25 14:00:00,捷運忠孝新生站(2號出口),2022-10-25 14:00:00,捷運公館站(3號出口),00:23:38,2022-10-25,500101181
2428826,2022-10-25 19:00:00,捷運忠孝新生站(2號出口),2022-10-25 19:00:00,捷運公館站(2號出口),00:22:16,2022-10-25,500101022
2429294,2022-10-25 12:00:00,臺大水源舍區B棟,2022-10-25 12:00:00,捷運公館站(1號出口),00:04:29,2022-10-25,500106003
2429454,2022-10-25 19:00:00,光華商場,2022-10-25 19:00:00,捷運公館站(4號出口),00:40:52,2022-10-25,500106004
2430186,2022-10-25 10:00:00,臺大樂學館東側,2022-10-25 12:00:00,捷運公館站(3號出口),01:57:19,2022-10-25,500101181

In [3]:
# "500101022": "YouBike2.0_捷運公館站(2號出口)"
# "500101181": "YouBike2.0_捷運公館站(3號出口)"
# "500106003": "YouBike2.0_捷運公館站(1號出口)"
# "500106004": "YouBike2.0_捷運公館站(4號出口)"
df_guan = pd.DataFrame(columns=['time', 'tot', 'sbi', 'bemp', 'act', 'station_id'])
station_guan_id = ["500106003", "500101022", "500101181", "500106004"]
for station_id in station_guan_id:
  for i in range(2,32):
    try:
      if i < 10:
        path = f'./html.2023.final.data/release/2023100{i}/{station_id}.json'
      else:
        path = f'./html.2023.final.data/release/202310{i}/{station_id}.json'
      df = pd.read_json(path)
      df = df.transpose()
      df = df.reset_index()

      # 更改日期，這裡將日期更改為 '2023-11-20'
      df['index'] = df['index'].apply(lambda dt: dt.replace(year=2023, month=10, day=i))
      df = df.rename(columns={'index':'time'})
      df['station_id'] = station_id
      # 顯示更新後的 DataFrame
      df_guan = pd.concat([df_guan, df], axis=0)
    except:
      continue
df_guan

In [ ]:
youbike_guan_df_tmp = youbike_guan_df.head(1000)
df_guan_tmp = df_guan.head(1000)
youbike_guan_df.to_csv("在公館借資料.csv")
youbike_guan_df2.to_csv("在公館還資料.csv")
df_guan.to_csv("每分鐘資料.csv")

### 開串

In [1]:
###讀資料進來
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

rent_df = pd.read_csv('./在公館借資料.csv')
rent_df.drop('Unnamed: 0', axis=1, inplace=True)
return_df = pd.read_csv('./在公館還資料.csv')
return_df.drop('Unnamed: 0', axis=1, inplace=True)
minute_df = pd.read_csv('./每分鐘資料.csv')
minute_df.drop('Unnamed: 0', axis=1, inplace=True)
mrt_df = pd.read_csv('./oct_MRT_data.csv')
mrt_df.rename(columns={'Unnamed: 0':'time','進站人次':'進站人數', '出站人次':'出站人數'}, inplace=True)

minute_df['time'] = pd.to_datetime(minute_df['time'])
rent_df['rent_time'] = pd.to_datetime(rent_df['rent_time'])
rent_df['return_time'] = pd.to_datetime(rent_df['return_time'])
return_df['rent_time'] = pd.to_datetime(return_df['rent_time'])
return_df['return_time'] = pd.to_datetime(return_df['return_time'])
# weather_df['time'] = pd.to_datetime(weather_df['time'])
mrt_df['time'] = pd.to_datetime(mrt_df['time'])

In [2]:
#把每10分鐘的資料取出來
minute_df1 = minute_df[minute_df['station_id'] == 500106003]
minute_df2 = minute_df[minute_df['station_id'] == 500101022]
minute_df3 = minute_df[minute_df['station_id'] == 500101181]
minute_df4 = minute_df[minute_df['station_id'] == 500106004]
minute_df1 = minute_df1.set_index('time').resample('10T').first().reset_index()
minute_df1['station_id'] = 500106003
minute_df2 = minute_df2.set_index('time').resample('10T').first().reset_index()
minute_df2['station_id'] = 500101022
minute_df3 = minute_df3.set_index('time').resample('10T').first().reset_index()
minute_df3['station_id'] = 500101181
minute_df4 = minute_df4.set_index('time').resample('10T').first().reset_index()
minute_df4['station_id'] = 500106004
minute_df_per10 = pd.concat([minute_df1, minute_df2, minute_df3, minute_df4], axis=0).reset_index().drop('index', axis=1)

### 捷運人數

In [3]:
#跟捷運資料left join
chained_data = pd.merge(minute_df_per10,mrt_df, on='time', how='left')
# chained_data.loc[chained_data['進站人數'].isnull(),'進站人數'] = 0
# chained_data.loc[chained_data['出站人數'].isnull(),'出站人數'] = 0

### 天氣

In [4]:
## 把天氣資料時間弄成datetime
weather_df = pd.read_csv('./october_weather.csv')
weather_df['觀測時間(hour)'] = weather_df['觀測時間(hour)'].replace(24, 0)
weather_df['date'] = pd.to_datetime(weather_df['date'])
weather_df['date'] = weather_df.apply(lambda x: x['date'] + pd.Timedelta(days=1) if x['觀測時間(hour)'] == 0 else x['date'], axis=1)
weather_df['date'] = pd.to_datetime(weather_df['date'].dt.strftime('%Y-%m-%d')+ " " + weather_df['觀測時間(hour)'].astype(str) + ":00:00")
weather_df.drop(['觀測時間(hour)','日照時數(h)', '能見度(km)', '總雲量(0~10)'], axis=1, inplace=True)
weather_df.rename(columns={'date':'time'}, inplace=True)

In [5]:
## 把天氣資料時間弄成10分鐘一筆
extend_weather = pd.DataFrame()

# 遍歷 df_weather DataFrame
for index, row in weather_df.iterrows():
    extend_weather = extend_weather.append(row, ignore_index=True)
    # 對於每一行，創建 5 個新行，對應於 10、20、30、40、50 分
    for minute in [10, 20, 30, 40, 50]:
        new_row = row.copy()
        new_row['time'] = new_row['time'].replace(minute=minute, second=0)
        extend_weather = extend_weather.append(new_row, ignore_index=True)

In [6]:
# 把天氣資料跟整體資料合併
chained_data = pd.merge(chained_data,extend_weather, on='time', how='left')

### 去年的借還數-借

In [7]:
rent_df['date'] = rent_df['rent_time'].dt.date
rent_df['hour'] = rent_df['rent_time'].dt.hour
group_rent = rent_df.groupby(['rent_station_id', 'date', 'hour']).count().reset_index()
group_rent = group_rent.iloc[:,:4]
group_rent.rename(columns={'rent_station_id':'station_id', 'rent_time':'count'}, inplace=True)
group_rent

      station_id        date  hour  count
0      500101022  2022-10-01     0     15
1      500101022  2022-10-01     1      1
2      500101022  2022-10-01     3      1
3      500101022  2022-10-01     6     19
4      500101022  2022-10-01     7     41
...          ...         ...   ...    ...
2507   500106004  2022-10-31    18      2
2508   500106004  2022-10-31    19      2
2509   500106004  2022-10-31    20      1
2510   500106004  2022-10-31    21      1
2511   500106004  2022-10-31    23      1

[2512 rows x 4 columns]

In [8]:
#把每小時資料補齊並填上0
from itertools import product
all_dates = pd.date_range(group_rent['date'].min(), group_rent['date'].max(), freq='D')
all_hours = range(24)
rent_stations = group_rent['station_id'].unique()
all_combinations = pd.DataFrame(product(rent_stations, all_dates, all_hours), columns=['station_id', 'date', 'hour'])

# 將 date 和 hour 合併成一個 datetime 欄位
all_combinations['date'] = pd.to_datetime(all_combinations['date'])
all_combinations['time'] = all_combinations.apply(lambda row: row['date'] + pd.Timedelta(hours=row['hour']), axis=1)
group_rent['date'] = pd.to_datetime(group_rent['date'])
merged_rent = pd.merge(all_combinations, group_rent, on=['station_id', 'date', 'hour'], how='left').fillna({'count': 0})

# 丟棄不再需要的 date 和 hour 欄位
merged_rent.drop(['date', 'hour'], axis=1, inplace=True)
merged_rent

      station_id                time  count
0      500101022 2022-10-01 00:00:00   15.0
1      500101022 2022-10-01 01:00:00    1.0
2      500101022 2022-10-01 02:00:00    0.0
3      500101022 2022-10-01 03:00:00    1.0
4      500101022 2022-10-01 04:00:00    0.0
...          ...                 ...    ...
2971   500106004 2022-10-31 19:00:00    2.0
2972   500106004 2022-10-31 20:00:00    1.0
2973   500106004 2022-10-31 21:00:00    1.0
2974   500106004 2022-10-31 22:00:00    0.0
2975   500106004 2022-10-31 23:00:00    1.0

[2976 rows x 3 columns]

In [9]:
# 把每10分鐘補進來，並且把每小時的資料除以6
extend_rent = pd.DataFrame()

for index, row in merged_rent.iterrows():
    new_row = row.copy()
    new_row['count'] /= 6
    extend_rent = extend_rent.append(new_row, ignore_index=True)
    # 對於每一行，創建 5 個新行，對應於 10、20、30、40、50 分
    for minute in [10, 20, 30, 40, 50]:
        new_row = row.copy()
        new_row['count'] /= 6
        new_row['time'] = new_row['time'].replace(minute=minute, second=0)
        extend_rent = extend_rent.append(new_row, ignore_index=True)
extend_rent

          count   station_id                time
0      2.500000  500101022.0 2022-10-01 00:00:00
1      2.500000  500101022.0 2022-10-01 00:10:00
2      2.500000  500101022.0 2022-10-01 00:20:00
3      2.500000  500101022.0 2022-10-01 00:30:00
4      2.500000  500101022.0 2022-10-01 00:40:00
...         ...          ...                 ...
17851  0.166667  500106004.0 2022-10-31 23:10:00
17852  0.166667  500106004.0 2022-10-31 23:20:00
17853  0.166667  500106004.0 2022-10-31 23:30:00
17854  0.166667  500106004.0 2022-10-31 23:40:00
17855  0.166667  500106004.0 2022-10-31 23:50:00

[17856 rows x 3 columns]

### 去年的借還數-還

In [10]:
return_df['date'] = return_df['rent_time'].dt.date
return_df['hour'] = return_df['rent_time'].dt.hour
group_return = return_df.groupby(['return_station_id', 'date', 'hour']).count().reset_index()
group_return = group_return.iloc[:,:4]
group_return.rename(columns={'return_station_id':'station_id', 'rent_time':'count'}, inplace=True)
group_return

      station_id        date  hour  count
0      500101022  2022-10-01     0      5
1      500101022  2022-10-01     2      1
2      500101022  2022-10-01     5      5
3      500101022  2022-10-01     6     22
4      500101022  2022-10-01     7     36
...          ...         ...   ...    ...
2448   500106004  2022-10-31    17      2
2449   500106004  2022-10-31    19      3
2450   500106004  2022-10-31    20      1
2451   500106004  2022-10-31    21      1
2452   500106004  2022-10-31    22      1

[2453 rows x 4 columns]

In [11]:
from itertools import product
all_dates = pd.date_range(group_return['date'].min(), group_return['date'].max(), freq='D')
all_hours = range(24)
return_stations = group_return['station_id'].unique()
all_combinations = pd.DataFrame(product(return_stations, all_dates, all_hours), columns=['station_id', 'date', 'hour'])

# 將 date 和 hour 合併成一個 datetime 欄位
all_combinations['date'] = pd.to_datetime(all_combinations['date'])
all_combinations['time'] = all_combinations.apply(lambda row: row['date'] + pd.Timedelta(hours=row['hour']), axis=1)
group_return['date'] = pd.to_datetime(group_return['date'])
merged_return = pd.merge(all_combinations, group_return, on=['station_id', 'date', 'hour'], how='left').fillna({'count': 0})

# 丟棄不再需要的 date 和 hour 欄位
merged_return.drop(['date', 'hour'], axis=1, inplace=True)
merged_return

      station_id                time  count
0      500101022 2022-10-01 00:00:00    5.0
1      500101022 2022-10-01 01:00:00    0.0
2      500101022 2022-10-01 02:00:00    1.0
3      500101022 2022-10-01 03:00:00    0.0
4      500101022 2022-10-01 04:00:00    0.0
...          ...                 ...    ...
2971   500106004 2022-10-31 19:00:00    3.0
2972   500106004 2022-10-31 20:00:00    1.0
2973   500106004 2022-10-31 21:00:00    1.0
2974   500106004 2022-10-31 22:00:00    1.0
2975   500106004 2022-10-31 23:00:00    0.0

[2976 rows x 3 columns]

In [12]:
extend_return = pd.DataFrame()

for index, row in merged_return.iterrows():
    new_row = row.copy()
    new_row['count'] /= 6
    extend_return = extend_return.append(new_row, ignore_index=True)
    # 對於每一行，創建 5 個新行，對應於 10、20、30、40、50 分
    for minute in [10, 20, 30, 40, 50]:
        new_row = row.copy()
        new_row['count'] /= 6
        new_row['time'] = new_row['time'].replace(minute=minute, second=0)
        extend_return = extend_return.append(new_row, ignore_index=True)
extend_return

          count   station_id                time
0      0.833333  500101022.0 2022-10-01 00:00:00
1      0.833333  500101022.0 2022-10-01 00:10:00
2      0.833333  500101022.0 2022-10-01 00:20:00
3      0.833333  500101022.0 2022-10-01 00:30:00
4      0.833333  500101022.0 2022-10-01 00:40:00
...         ...          ...                 ...
17851  0.000000  500106004.0 2022-10-31 23:10:00
17852  0.000000  500106004.0 2022-10-31 23:20:00
17853  0.000000  500106004.0 2022-10-31 23:30:00
17854  0.000000  500106004.0 2022-10-31 23:40:00
17855  0.000000  500106004.0 2022-10-31 23:50:00

[17856 rows x 3 columns]

In [13]:
#變成2023年才能join (因為借還車資料是2022年)
extend_rent['time'] = extend_rent['time'].apply(lambda dt: dt.replace(year=2023))
extend_return['time'] = extend_return['time'].apply(lambda dt: dt.replace(year=2023))

### Final

In [14]:
chained_data = pd.merge(chained_data, extend_rent, on=['time', 'station_id'], how='left')
chained_data.rename(columns={'count':'去年借車數'}, inplace=True)
chained_data = pd.merge(chained_data, extend_return, on=['time', 'station_id'], how='left')
chained_data.rename(columns={'count':'去年還車數'}, inplace=True)
chained_data

,time,tot,sbi,bemp,act,station_id,進站人數,出站人數,全天空日射量(MJ/㎡),最大瞬間風(m/s),...,測站氣壓(hPa),相對溼度(%),紫外線指數,降水時數(h),降水量(mm),露點溫度(℃),風向(360degree),風速(m/s),去年借車數,去年還車數
0,2023-10-02 00:00:00,12.0,0.0,12.0,1.0,500106003,42.0,21.0,0.0,4.7,...,1009.3,83.0,0.0,0.0,0.0,23.4,130,2.0,0.333333,0.166667
1,2023-10-02 00:10:00,12.0,0.0,12.0,1.0,500106003,1.0,0.0,0.0,4.7,...,1009.3,83.0,0.0,0.0,0.0,23.4,130,2.0,0.333333,0.166667
2,2023-10-02 00:20:00,12.0,0.0,12.0,1.0,500106003,1.0,0.0,0.0,4.7,...,1009.3,83.0,0.0,0.0,0.0,23.4,130,2.0,0.333333,0.166667
3,2023-10-02 00:30:00,12.0,0.0,12.0,1.0,500106003,1.0,0.0,0.0,4.7,...,1009.3,83.0,0.0,0.0,0.0,23.4,130,2.0,0.333333,0.166667
4,2023-10-02 00:40:00,12.0,0.0,12.0,1.0,500106003,1.0,0.0,0.0,4.7,...,1009.3,83.0,0.0,0.0,0.0,23.4,130,2.0,0.333333,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17275,2023-10-31 23:10:00,12.0,2.0,10.0,1.0,500106004,NaN,NaN,0.0,9.2,...,1016.8,94.0,0.0,0.1,T,21.2,90,2.8,0.166667,0.000000
17276,2023-10-31 23:20:00,12.0,1.0,11.0,1.0,500106004,NaN,NaN,0.0,9.2,...,1016.8,94.0,0.0,0.1,T,21.2,90,2.8,0.166667,0.000000
17277,2023-10-31 23:30:00,12.0,0.0,12.0,1.0,500106004,NaN,NaN,0.0,9.2,...,1016.8,94.0,0.0,0.1,T,21.2,90,2.8,0.166667,0.000000
17278,2023-10-31 23:40:00,12.0,0.0,12.0,1.0,500106004,NaN,NaN,0.0,9.2,...,1016.8,94.0,0.0,0.1,T,21.2,90,2.8,0.166667,0.000000
17279,2023-10-31 23:50:00,12.0,0.0,12.0,1.0,500106004,NaN,NaN,0.0,9.2,...,1016.8,94.0,0.0,0.1,T,21.2,90,2.8,0.166667,0.000000

In [15]:
#把時間資訊變成欄位
chained_data['weekday'] = chained_data['time'].dt.weekday
chained_data['monthday'] = chained_data['time'].dt.day
chained_data['hour'] = chained_data['time'].dt.hour
chained_data['minute'] = chained_data['time'].dt.minute

In [16]:
#10月這幾天沒有資料
chained_data[chained_data.isnull().any(axis=1)]['monthday'].unique()

array([11, 12, 13, 14, 15, 21, 22, 23, 24, 31], dtype=int64)

In [17]:
#定義是不是國定假日
holiday = [1,7,8,10,14,15,21,22,28,29]
chained_data['is_holiday'] = chained_data['monthday'].isin(holiday).astype(int)
#尖峰時段-可能需要更多定義
high_traffic = [8,9,10,11,12,13,14,15,16,17,18,19,20]
chained_data['is_hightraffic'] = chained_data['hour'].isin(high_traffic).astype(int)

In [18]:
#把station_id做onehot encoding
one_hot_encoded = pd.get_dummies(chained_data['station_id'], prefix='station_id')
chained_data = pd.concat([chained_data, one_hot_encoded], axis=1)

In [19]:
chained_data.rename(columns={'station_id_500101022':'公館2號', 'station_id_500101181':'公館3號','station_id_500106003':'公館1號', 'station_id_500106004':'公館4號'}, inplace=True)
chained_data.drop(['station_id','monthday'], axis=1, inplace=True)

In [20]:
#後來才發現有些缺失值
chained_data['降水量(mm)'].replace('T', np.nan, inplace=True)
chained_data['風向(360degree)'].replace('V', np.nan, inplace=True)

In [21]:
chained_data['降水量(mm)']= chained_data['降水量(mm)'].astype(float)
chained_data['風向(360degree)']=chained_data['風向(360degree)'].astype(float)

### 轉時間變成sin cos

In [22]:
import math
chained_data['weekday_sin'] = chained_data['weekday'].apply(lambda x: math.sin(x*2*math.pi/7))
chained_data['weekday_cos'] = chained_data['weekday'].apply(lambda x: math.cos(x*2*math.pi/7))
chained_data['time_code'] = (chained_data['hour']*6) + (chained_data['minute']/10)
chained_data['time_sin'] = chained_data['time_code'].apply(lambda x: math.sin(x*2*math.pi/144))
chained_data['time_cos'] = chained_data['time_code'].apply(lambda x: math.cos(x*2*math.pi/144))

In [23]:
chained_data.drop(['time_code','weekday','hour','minute'], axis=1, inplace=True)

In [25]:
chained_data.columns[chained_data.isnull().any()].tolist()

['tot', 'sbi', 'bemp', 'act', '進站人數', '出站人數', '降水量(mm)', '風向(360degree)']

In [26]:
chained_data.to_csv("./chained_data(把time欄位給drop掉就可以用了).csv", index=False, encoding='utf-8-sig')

### 補資料

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv('./chained_data(把time欄位給drop掉就可以用了).csv')
df['time'] = pd.to_datetime(df['time'])

In [28]:
guan_1 = df[df['公館1號'] == 1]
guan_2 = df[df['公館2號'] == 1]
guan_3 = df[df['公館3號'] == 1]
guan_4 = df[df['公館4號'] == 1]

In [29]:
#用forward fill跟backward fill的平均來填補缺失值
def mean_fill(f,b):
    mean_f = []
    for i in f.index:
        if math.isnan(f[i]):
            mean_f.append(b[i])
        elif math.isnan(b[i]):
            mean_f.append(f[i])
        else:
            mean_f.append((f[i]+b[i])/2)
    return mean_f
for col in ['進站人數', '出站人數', '降水量(mm)', '風向(360degree)']:
    f_fill = guan_1[col].fillna(method='ffill')
    b_fill = guan_1[col].fillna(method='bfill')
    m_fill = mean_fill(f_fill,b_fill)
    guan_1[col] = m_fill
    f_fill = guan_2[col].fillna(method='ffill')
    b_fill = guan_2[col].fillna(method='bfill')
    m_fill = mean_fill(f_fill,b_fill)
    guan_2[col] = m_fill
    f_fill = guan_3[col].fillna(method='ffill')
    b_fill = guan_3[col].fillna(method='bfill')
    m_fill = mean_fill(f_fill,b_fill)
    guan_3[col] = m_fill
    f_fill = guan_4[col].fillna(method='ffill')
    b_fill = guan_4[col].fillna(method='bfill')
    m_fill = mean_fill(f_fill,b_fill)
    guan_4[col] = m_fill

<ipython-input-29-76b0563ccdcf>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_1[col] = m_fill
<ipython-input-29-76b0563ccdcf>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_2[col] = m_fill
<ipython-input-29-76b0563ccdcf>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_3[col] = m_fill
<ipython-input-29-76b0563ccdcf>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_4[col] = m_fill

In [30]:
guan_1['tot'] = guan_1['tot'].fillna(method='ffill')
guan_2['tot'] = guan_2['tot'].fillna(method='ffill')
guan_3['tot'] = guan_3['tot'].fillna(method='ffill')
guan_4['tot'] = guan_4['tot'].fillna(method='ffill')

<ipython-input-30-8e84ad1a5961>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_1['tot'] = guan_1['tot'].fillna(method='ffill')
<ipython-input-30-8e84ad1a5961>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_2['tot'] = guan_2['tot'].fillna(method='ffill')
<ipython-input-30-8e84ad1a5961>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_3['tot'] = guan_3['tot'].fillna(method='ffill')
<ipython-input-30-8e84ad1a5961>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  guan_4['tot'] = guan_4['tot'].fillna(method='ffill')

In [31]:
def mean_fill(df):
    sbi_list = []
    act_list = []
    for index, row in df.iterrows():
        if pd.isna(row['sbi']):
            missing_date = row['time']
            # 計算同一 weekday 和時間點的前三週數據的平均值
            count = 0
            cum_sbi = 0
            for i in range(1,10):
                if len(df[df['time'] == missing_date - pd.DateOffset(weeks=i)]) != 0 and ~np.isnan(df[df['time'] == missing_date - pd.DateOffset(weeks=i)]['sbi'].values[0]):
                    cum_sbi += df[df['time'] == missing_date - pd.DateOffset(weeks=i)]['sbi'].values[0]
                    count += 1
                if len(df[df['time'] == missing_date + pd.DateOffset(weeks=i)]) != 0 and ~np.isnan(df[df['time'] == missing_date + pd.DateOffset(weeks=i)]['sbi'].values[0]):
                    cum_sbi += df[df['time'] == missing_date + pd.DateOffset(weeks=i)]['sbi'].values[0]
                    count += 1
            if count == 0:
                average_value = 0
            else:
                average_value = round(cum_sbi/count)
            sbi_list.append(average_value)
        else:
            sbi_list.append(row['sbi'])
        if pd.isna(row['act']):
            missing_date = row['time']
            # 計算同一 weekday 和時間點的前三週數據的平均值
            one_count = 0
            zero_count = 0
            for i in range(1,10):
                if len(df[df['time'] == missing_date - pd.DateOffset(weeks=i)]) != 0:
                    if df[df['time'] == missing_date - pd.DateOffset(weeks=i)]['act'].values[0] == 1:
                        one_count += 1
                    else:
                        zero_count += 1
                if len(df[df['time'] == missing_date + pd.DateOffset(weeks=i)]) != 0:
                    if df[df['time'] == missing_date + pd.DateOffset(weeks=i)]['act'].values[0] == 1:
                        one_count += 1
                    else:
                        zero_count += 1
            if one_count > zero_count:
                average_value = 1
            else:
                average_value = 0
            act_list.append(average_value)
        else:
            act_list.append(row['act'])
    df['sbi'] = sbi_list
    df['act'] = act_list
    return df
guan_1 = mean_fill(guan_1)
guan_2 = mean_fill(guan_2)
guan_3 = mean_fill(guan_3)
guan_4 = mean_fill(guan_4)
df = pd.concat([guan_1, guan_2, guan_3, guan_4], axis=0).reset_index().drop('index', axis=1)
df['bemp'] = df['tot'] - df['sbi']

<ipython-input-31-f609502711a3>:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sbi'] = sbi_list
<ipython-input-31-f609502711a3>:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['act'] = act_list

In [32]:
df.to_csv("./chained_data(補完值).csv", index=False, encoding='utf-8-sig')

### 試試看而已

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('./chained_data(補完值).csv')
df['time'] = pd.to_datetime(df['time'])

In [2]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Preparing the data
# Dropping the 'time' column as mentioned in the file name

data_train = df[df['time'] >= '2023-10-24']
data_test = df[df['time'] < '2023-10-24']
data_train = data_train.drop(columns=['time'])
data_test = data_test.drop(columns=['time'])
# Separating the target variable 'sbi' from the features
X_train = data_train.drop(columns=['sbi'])
y_train = data_train['sbi']
X_test = data_test.drop(columns=['sbi'])
y_test= data_test['sbi']

# Splitting the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating and training the XGBoost model
model = XGBRegressor(objective='reg:squarederror', n_estimators=1000, max_depth=10, learning_rate=0.1, random_state=42)
model.fit(X_train, y_train)

# Predicting and evaluating the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

mse, rmse

(0.03069670378650329, 0.17520474818481171)

In [6]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Preparing the data
# Dropping the 'time' column as mentioned in the file name
data_train = df[df['time'] >= '2023-10-24']
data_test = df[df['time'] < '2023-10-24']
data_train = data_train.drop(columns=['time'])
data_test = data_test.drop(columns=['time'])

# Separating the target variable 'sbi' from the features
X_train = data_train.drop(columns=['sbi'])
y_train = data_train['sbi']
X_test = data_test.drop(columns=['sbi'])
y_test = data_test['sbi']

# Creating and training the LightGBM model
model = lgb.LGBMRegressor(objective='regression', num_leaves=31, learning_rate=0.1, n_estimators=1000, max_depth=10, random_state=42)
model.fit(X_train, y_train)

# Predicting and evaluating the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

mse, rmse

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000807 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1363
[LightGBM] [Info] Number of data points in the train set: 4608, number of used features: 29
[LightGBM] [Info] Start training from score 13.261719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

(0.05775236801187663, 0.24031722371040456)